### ISSUE TITLE
constant parsing at end of buffer?

### ISSUE THREAD

**Issue by knightmansmountain** [SimuPoLAS/blocky#7] opened 2017-09-11 08:41 UTC
What happens if a list that has to be parsed constant is split in two buffers?
Wouldn't the char parser just parse the part of the list that ends in the first buffer and would continue in the second?

**Comment by UgiNyaa** [comment] 2017-09-12 16:28
Behaviour confirmed.

This has to be fixed in the rare case that a part, that has to be parsed contant, is situated partly and the ending of one buffer and at the beginning of the next.

My first guess would be to enhance the try_parse method of Parser to be able to return more than just a bool. It should be no problem for try_parse to determin whether it can not parse, because the buffer is to short and there may come more, that would result in valid parsing. The result of try_parse will be checked, and if its the code for too short buffer, the parsing stops and it will be reloaded.

Something like error codes? Like in parse_constant and parse_variable?

If there are no better ideas, I will implement it like that.

**Closed** 2017-12-11 10:25 UTC
Labels: bug
